import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const schemaSql = readFileSync(new URL('../../supabase/migrations/20260820213626_create_adreem_v3_schema.sql', import.meta.url), 'utf8')
const ledgerSql = readFileSync(new URL('../../supabase/migrations/20260820213628_create_adreem_v3_ledger_functions.sql', import.meta.url), 'utf8')
const legacyCleanupSql = readFileSync(new URL('../../supabase/migrations/20260820213833_remove_empty_legacy_state_from_v3.sql', import.meta.url), 'utf8')
const summaryScopeSql = readFileSync(new URL('../../supabase/migrations/20260822090000_add_summary_scope_and_record_only.sql', import.meta.url), 'utf8')
const accountDeletionSql = readFileSync(new URL('../../supabase/migrations/20260822170000_add_unused_account_deletion.sql', import.meta.url), 'utf8')
const movementInvariantSql = readFileSync(new URL('../../supabase/migrations/20260822193000_harden_movement_invariants.sql', import.meta.url), 'utf8')
const movementIdentitySql = readFileSync(new URL('../../supabase/migrations/20260822232245_lock_movement_type_and_currency.sql', import.meta.url), 'utf8')
const tryCurrencySql = readFileSync(new URL('../../supabase/migrations/20260823160000_add_try_currency.sql', import.meta.url), 'utf8')
const botRemovalSql = readFileSync(new URL('../../supabase/migrations/20260823190000_remove_telegram_bot.sql', import.meta.url), 'utf8')

describe('ADREEM v3 database migration invariants', () => {
  it('keeps financial numbers inside the exact application range', () => {
    expect(schemaSql).not.toContain('numeric(20, 0)')
    expect(schemaSql).toContain('balance_dinar numeric(15, 0)')
    expect(schemaSql).toContain('amount numeric(15, 0)')
    expect(schemaSql).toContain('rate numeric(15, 8)')
    expect(schemaSql).toContain('structure_locked boolean not null default false')
    expect(ledgerSql).toContain('delta numeric(15, 0)')
    expect(ledgerSql).toContain('abs(v_amount) > 999999999999999')
    expect(ledgerSql).toContain('v_rate > 9999999')
  })

  it('requires explicit membership in every authenticated ledger function', () => {
    expect(schemaSql).toContain('is_active boolean not null default false')
    expect(schemaSql).toContain("'adreem_member'")
    expect(ledgerSql.match(/ADREEM_MEMBERSHIP_REQUIRED/g)).toHaveLength(3)
    expect(ledgerSql).toContain("movement.movement_type <> 'opening_balance'")
    expect(ledgerSql).toContain('adreem_private.handle_new_auth_user()')
    expect(ledgerSql).toContain('create trigger adreem_on_auth_user_created')
    expect(ledgerSql).toContain("lower(coalesce(new.raw_app_meta_data ->> 'adreem_member', 'false'))")
  })

  it('keeps row isolation forced and movement search indexed', () => {
    expect(schemaSql.match(/force row level security;/g)?.length).toBeGreaterThanOrEqual(10)
    expect(schemaSql).toContain('adreem_movements_note_trgm_idx')
    expect(schemaSql).toContain('adreem_attachments_account_recent_idx')
    expect(schemaSql).toContain('adreem_reconciliations_account_recent_idx')
    expect(schemaSql).toContain('extensions.gin_trgm_ops')
    expect(schemaSql).toContain('adreem_normalize_search_text')
    expect(ledgerSql).toContain('public.adreem_normalize_search_text(p_query)')
  })

  it('enforces movement immutability and blocks browser resets in the database', () => {
    expect(ledgerSql).toContain('ADREEM_CLIENT_RESET_NOT_ALLOWED')
    expect(ledgerSql).toContain('ADREEM_VOIDED_MOVEMENT_IMMUTABLE')
    expect(ledgerSql).toContain('ADREEM_MOVEMENT_CREATED_AT_IMMUTABLE')
    expect(ledgerSql).toContain('ADREEM_MOVEMENT_EDIT_WINDOW_EXPIRED')
    expect(ledgerSql.match(/least\(v_existing_movement_occurred_at, v_existing_movement_created_at\)/g)).toHaveLength(2)
    expect(ledgerSql).toContain('ADREEM_NONZERO_ACCOUNT_CANNOT_BE_DISABLED')
    expect(ledgerSql).toContain('ADREEM_NEGATIVE_OWN_BALANCE')
    expect(ledgerSql).toContain('ADREEM_ACTIVE_RECURRING_RULE_LIMIT')
    expect(ledgerSql).toContain('adreem_merge_account_references')
    expect(ledgerSql).toContain('ADREEM_INVALID_MOVEMENT_STATUS_TRANSITION')
    expect(ledgerSql).toContain('ADREEM_MOVEMENT_VOID_WINDOW_EXPIRED')
    expect(ledgerSql).toContain('public.adreem_latest_account_attachments')
    expect(ledgerSql).toContain('public.adreem_latest_reconciliations')
    expect(ledgerSql).toContain("least(coalesce(\n        nullif(v_item ->> 'createdAt'")
    expect(ledgerSql).not.toContain('reconciled_at = excluded.reconciled_at')
    expect(ledgerSql).toContain('cross join lateral')
    expect(ledgerSql).not.toContain('row_number() over')
  })

  it('removes the retired bot state without touching ledger records', () => {
    expect(botRemovalSql).toContain('create or replace function adreem_private.handle_new_auth_user()')
    expect(botRemovalSql).not.toContain("new.raw_app_meta_data ->> 'adreem_telegram_user_id'")
    expect(botRemovalSql).toContain("raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) - 'adreem_telegram_user_id'")
    expect(botRemovalSql.match(/drop function if exists public\.adreem_bot_state_/g)).toHaveLength(13)
    expect(botRemovalSql).toContain('drop table if exists adreem_private.adreem_bot_state')
    expect(botRemovalSql).toContain('alter table public.adreem_profiles drop column if exists telegram_user_id')
    expect(botRemovalSql).not.toMatch(/delete from public\.adreem_(accounts|movements|movement_entries)/)
  })

  it('removes the legacy blob tables only from an empty v3 target', () => {
    expect(legacyCleanupSql).toContain("to_regclass('public.adreem_ledgers')")
    expect(legacyCleanupSql).toContain("raise exception 'ADREEM_LEGACY_STATE_NOT_EMPTY'")
    expect(legacyCleanupSql).toContain("raise exception 'ADREEM_LEGACY_BACKUP_NOT_EMPTY'")
    expect(legacyCleanupSql).toContain("execute 'lock table public.ml_state in access exclusive mode'")
    expect(legacyCleanupSql).toContain("execute 'lock table adreem_private.ml_state_backup_20260819 in access exclusive mode'")
    expect(legacyCleanupSql.indexOf("raise exception 'ADREEM_LEGACY_STATE_NOT_EMPTY'"))
      .toBeLessThan(legacyCleanupSql.indexOf("execute 'drop table public.ml_state'"))
    expect(legacyCleanupSql.indexOf("raise exception 'ADREEM_LEGACY_BACKUP_NOT_EMPTY'"))
      .toBeLessThan(legacyCleanupSql.indexOf("execute 'drop table adreem_private.ml_state_backup_20260819'"))
  })

  it('supports record-only movements without permitting a silent posting-mode change', () => {
    expect(summaryScopeSql).toContain("'record_only'")
    expect(summaryScopeSql).toContain('ADREEM_RECORD_ONLY_NOTE_REQUIRED')
    expect(summaryScopeSql).toContain('ADREEM_RECORD_ONLY_ACCOUNTS_NOT_ALLOWED')
    expect(summaryScopeSql).toContain('ADREEM_MOVEMENT_POSTING_MODE_IMMUTABLE')
    expect(summaryScopeSql).toContain('create trigger adreem_prevent_record_only_mode_flip')
    expect(summaryScopeSql).toContain("when 'record_only' then")
  })

  it('deletes only unused accounts under an owner-scoped revision lock', () => {
    expect(accountDeletionSql).toContain('function public.adreem_delete_unused_account')
    expect(accountDeletionSql).toContain('for update;')
    expect(accountDeletionSql).toContain('ADREEM_REVISION_CONFLICT')
    expect(accountDeletionSql).toContain('ADREEM_ACCOUNT_DELETE_IN_USE')
    expect(accountDeletionSql).toContain('ADREEM_ACCOUNT_DELETE_LINKED')
    expect(accountDeletionSql).toContain('from public.adreem_movement_entries')
    expect(accountDeletionSql).toContain('from public.adreem_attachments')
    expect(accountDeletionSql).toContain('from public.adreem_reconciliations')
    expect(accountDeletionSql).toContain('from public.adreem_recurring_rules')
    expect(accountDeletionSql).toContain('delete from public.adreem_audit_events')
    expect(accountDeletionSql).toContain("'unused_account_deleted'")
    expect(accountDeletionSql).toContain('to authenticated, service_role;')
  })

  it('keeps opening balances creation-only and rejects incomplete financial effects', () => {
    expect(movementInvariantSql).toContain('ADREEM_CORRECTION_NOTE_REQUIRED')
    expect(movementInvariantSql.match(/ADREEM_EXCHANGE_RESULT_TOO_SMALL/g)).toHaveLength(2)
    expect(movementInvariantSql).toContain('ADREEM_OPENING_MOVEMENT_IMMUTABLE')
    expect(movementInvariantSql).toContain("new.payload ->> 'mergedFromAccountId' = old.destination_account_id")
    expect(movementInvariantSql).toContain("if tg_op = 'DELETE'")
    expect(movementInvariantSql).toContain("old.movement_type = 'opening_balance' or new.movement_type = 'opening_balance'")
    expect(movementInvariantSql).toContain('ADREEM_OPENING_MOVEMENT_MISMATCH')
    expect(movementInvariantSql).toContain('ADREEM_OPENING_MOVEMENT_DUPLICATE')
    expect(movementInvariantSql).toContain('and movement.currency = new.currency')
    expect(movementInvariantSql).toContain("new.record_id = concat(")
    expect(movementInvariantSql).toContain("account.payload ->> 'openingDinar'")
    expect(movementInvariantSql).toContain("account.payload ->> 'openingUsd'")
    expect(movementInvariantSql).toContain('account.created_at = transaction_timestamp()')
    expect(movementInvariantSql).toContain('before insert or update or delete on public.adreem_movements')
    expect(movementInvariantSql).toContain('ADREEM_ACCOUNT_OPENING_IMMUTABLE')
    expect(movementInvariantSql).toContain("movement.payload ->> 'mergedFromAccountId' = new.record_id")
    expect(movementInvariantSql).toContain('movement.destination_account_id = v_merge_target_id')
    expect(movementInvariantSql).toContain("new.payload - array['destinationAccountId', 'mergedFromAccountId', 'updatedAt']")
    expect(movementInvariantSql).toContain("new.payload - array['status', 'openingDinar', 'openingUsd', 'mergedIntoAccountId', 'disabledAt', 'updatedAt']")
    expect(ledgerSql).toContain("'openingDinar', 0")
    expect(ledgerSql).toContain("'openingUsd', 0")
    expect(movementInvariantSql).toContain('ADREEM_ACCOUNT_OPENING_MOVEMENT_REQUIRED')
    expect(movementInvariantSql).toContain('into v_current_payload')
    expect(movementInvariantSql).toContain("v_current_payload ->> 'openingDinar'")
    expect(ledgerSql).toContain("v_existing_movement_payload - 'updatedAt' is not distinct from v_item - 'updatedAt'")
    expect(ledgerSql).toContain('continue;')
    expect(movementInvariantSql).toContain('create trigger adreem_protect_account_opening_amounts')
    expect(movementInvariantSql).toContain('create constraint trigger adreem_require_account_opening_movements')
    expect(movementInvariantSql).toContain('deferrable initially deferred')
  })

  it('locks the movement type and currency in both columns and payload', () => {
    expect(movementIdentitySql).toContain('function adreem_private.protect_movement_identity()')
    expect(movementIdentitySql.match(/old\.status = 'posted'/g)).toHaveLength(2)
    expect(movementIdentitySql).toContain('old.movement_type is distinct from new.movement_type')
    expect(movementIdentitySql).toContain("old.payload ->> 'type'")
    expect(movementIdentitySql).toContain('ADREEM_MOVEMENT_TYPE_IMMUTABLE')
    expect(movementIdentitySql).toContain('old.currency is distinct from new.currency')
    expect(movementIdentitySql).toContain("old.payload ->> 'currency'")
    expect(movementIdentitySql).toContain('ADREEM_MOVEMENT_CURRENCY_IMMUTABLE')
    expect(movementIdentitySql).toContain('before update on public.adreem_movements')
    expect(movementIdentitySql).toContain('revoke all on function adreem_private.protect_movement_identity()')
  })

  it('posts TRY through balances, openings, reports, and protected account lifecycles', () => {
    expect(tryCurrencySql).toContain('balance_try numeric(15, 0) not null default 0')
    expect(tryCurrencySql).toContain("currency_kind in ('LYD', 'USD', 'TRY', 'multi')")
    expect(tryCurrencySql).toContain("currency in ('LYD', 'USD', 'TRY')")
    expect(tryCurrencySql).toContain('adreem_accounts_nonnegative_try_check')
    expect(tryCurrencySql.match(/ADREEM_EXCHANGE_RESULT_TOO_SMALL/g)).toHaveLength(2)
    expect(tryCurrencySql).toContain("when 'transfer', 'cash_deposit', 'cash_withdrawal' then")
    expect(tryCurrencySql).toContain('create trigger adreem_sync_try_entry_balance')
    expect(tryCurrencySql).toContain('after insert or delete on public.adreem_movement_entries')
    expect(tryCurrencySql).toContain('create trigger adreem_sync_try_entry_balance_update')
    expect(tryCurrencySql).toContain('referencing old table as old_try_entries new table as new_try_entries')
    expect(tryCurrencySql).toContain('for each statement execute function adreem_private.sync_try_entry_balance_update()')
    expect(tryCurrencySql).toContain("foreach v_currency in array array['LYD', 'USD', 'TRY']")
    expect(tryCurrencySql).toContain("movement.record_id = concat('opening-', new.record_id, '-', v_suffix)")
    expect(tryCurrencySql).toContain("'incomeTry'")
    expect(tryCurrencySql).toContain("'expenseTry'")
    expect(tryCurrencySql).toContain("'netTry'")
    expect(tryCurrencySql).toContain("'try', coalesce(sum(abs(movement.amount)) filter (where movement.currency = 'TRY'), 0)")
  })
})
