-- ADREEM v3 relational ledger foundation.
-- This migration is additive: the legacy ml_state rows remain untouched until
-- the verified data migration and cutover are completed.

create schema if not exists adreem_private;
revoke all on schema adreem_private from public, anon, authenticated, service_role;

create table public.adreem_profiles (
  id uuid primary key references auth.users(id) on delete restrict,
  email text not null,
  display_name text not null default '',
  telegram_user_id bigint unique,
  language text not null default 'ar' check (language in ('ar', 'en')),
  is_system_owner boolean not null default false,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index adreem_profiles_email_key
  on public.adreem_profiles (lower(email));

create table public.adreem_ledgers (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references public.adreem_profiles(id) on delete restrict,
  legacy_ledger_id text unique,
  name text not null default 'ADREEM',
  version smallint not null default 3 check (version >= 3),
  revision bigint not null default 0 check (revision >= 0),
  reset_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, owner_id)
);

create table public.adreem_accounts (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  name text not null,
  account_type text not null check (account_type in ('person', 'cash', 'bank', 'expense', 'asset', 'project', 'summary', 'review')),
  value_kind text not null check (value_kind in ('cash', 'bank', 'receivable', 'expense', 'asset', 'project', 'summary', 'review')),
  currency_kind text not null check (currency_kind in ('LYD', 'USD', 'multi')),
  status text not null default 'active' check (status in ('active', 'inactive', 'needs_review')),
  balance_dinar numeric(15, 0) not null default 0,
  balance_usd numeric(15, 0) not null default 0,
  posted_count bigint not null default 0 check (posted_count >= 0),
  structure_locked boolean not null default false,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade,
  check (
    (account_type = 'person' and value_kind = 'receivable') or
    (account_type = 'cash' and value_kind = 'cash') or
    (account_type = 'bank' and value_kind = 'bank') or
    (account_type = 'expense' and value_kind = 'expense') or
    (account_type = 'asset' and value_kind = 'asset') or
    (account_type = 'project' and value_kind = 'project') or
    (account_type = 'summary' and value_kind = 'summary') or
    (account_type = 'review' and value_kind = 'review')
  ),
  check (
    value_kind not in ('cash', 'bank', 'asset') or
    (balance_dinar >= 0 and balance_usd >= 0)
  )
);

create table public.adreem_dimensions (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  name text not null default '',
  status text not null default 'active' check (status in ('active', 'inactive')),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade
);

create table public.adreem_movements (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  sequence bigint generated by default as identity,
  movement_type text not null check (movement_type in (
    'opening_balance', 'transfer', 'cash_deposit', 'cash_withdrawal',
    'expense', 'truck_expense', 'truck_income', 'usd_sale',
    'usd_purchase', 'external_income', 'correction'
  )),
  status text not null check (status in ('draft', 'needs_review', 'posted', 'voided')),
  amount numeric(15, 0),
  currency text check (currency is null or currency in ('LYD', 'USD')),
  source_account_id text,
  destination_account_id text,
  rate numeric(15, 8),
  dimension_id text,
  expense_category_id text,
  occurred_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  unique (ledger_id, sequence),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade,
  foreign key (ledger_id, source_account_id)
    references public.adreem_accounts(ledger_id, record_id) deferrable initially deferred,
  foreign key (ledger_id, destination_account_id)
    references public.adreem_accounts(ledger_id, record_id) deferrable initially deferred,
  foreign key (ledger_id, dimension_id)
    references public.adreem_dimensions(ledger_id, record_id) deferrable initially deferred,
  foreign key (ledger_id, expense_category_id)
    references public.adreem_accounts(ledger_id, record_id) deferrable initially deferred,
  check (status <> 'posted' or (amount is not null and amount <> 0 and currency is not null)),
  check (rate is null or rate > 0)
);

create table public.adreem_movement_entries (
  ledger_id uuid not null,
  owner_id uuid not null,
  movement_id text not null,
  entry_index smallint not null check (entry_index >= 0),
  account_id text not null,
  currency text not null check (currency in ('LYD', 'USD')),
  delta numeric(15, 0) not null check (delta <> 0),
  created_at timestamptz not null default now(),
  primary key (ledger_id, movement_id, entry_index),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade,
  foreign key (ledger_id, movement_id)
    references public.adreem_movements(ledger_id, record_id) on delete cascade,
  foreign key (ledger_id, account_id)
    references public.adreem_accounts(ledger_id, record_id) on delete restrict
);

create table public.adreem_attachments (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  movement_id text,
  account_id text,
  storage_path text,
  file_name text not null default '',
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  hidden_at timestamptz,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  unique (ledger_id, storage_path),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade,
  foreign key (ledger_id, movement_id)
    references public.adreem_movements(ledger_id, record_id) on delete cascade,
  foreign key (ledger_id, account_id)
    references public.adreem_accounts(ledger_id, record_id) on delete cascade,
  check (movement_id is not null or account_id is not null),
  check (storage_path is not null),
  check (nullif(payload ->> 'url', '') is null or nullif(payload ->> 'url', '') ~ '^https://'),
  check (
    storage_path is null or (
      storage_path like owner_id::text || '/' || ledger_id::text || '/_%' and
      storage_path not like '%..%'
    )
  )
);

create table public.adreem_recurring_rules (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  next_run_at timestamptz,
  last_run_at timestamptz,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade
);

create table public.adreem_reconciliations (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  account_id text not null,
  reconciled_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade,
  foreign key (ledger_id, account_id)
    references public.adreem_accounts(ledger_id, record_id) on delete restrict
);

create table public.adreem_audit_events (
  ledger_id uuid not null,
  owner_id uuid not null,
  record_id text not null,
  action text not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  primary key (ledger_id, record_id),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade
);

create table public.adreem_ignored_external_accounts (
  ledger_id uuid not null,
  owner_id uuid not null,
  account_id text not null,
  created_at timestamptz not null default now(),
  primary key (ledger_id, account_id),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete cascade
);

create table adreem_private.adreem_bot_state (
  bot_key text not null,
  state_key text not null,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (bot_key, state_key)
);

create table adreem_private.adreem_security_events (
  id bigint generated always as identity primary key,
  ledger_id uuid not null,
  owner_id uuid not null,
  action text not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now(),
  foreign key (ledger_id, owner_id)
    references public.adreem_ledgers(id, owner_id) on delete restrict
);

comment on table public.adreem_audit_events is
  'User-visible activity history. Security evidence is stored separately in adreem_private.adreem_security_events.';

create index adreem_accounts_owner_status_idx
  on public.adreem_accounts (owner_id, status, updated_at desc);
create index adreem_movements_owner_occurred_idx
  on public.adreem_movements (owner_id, occurred_at desc, record_id desc);
create index adreem_movements_owner_sequence_idx
  on public.adreem_movements (owner_id, sequence desc);
create index adreem_movements_owner_status_idx
  on public.adreem_movements (owner_id, status, occurred_at desc);
create schema if not exists extensions;
create extension if not exists pg_trgm with schema extensions;

create or replace function public.adreem_normalize_search_text(p_value text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select lower(btrim(regexp_replace(
    translate(
      regexp_replace(normalize(coalesce(p_value, ''), NFKC), '[ؐ-ًؚ-ٰٟۖ-ۭـ]', '', 'g'),
      'أإآى',
      'اااي'
    ),
    '\s+',
    ' ',
    'g'
  )));
$$;

create index adreem_movements_note_trgm_idx
  on public.adreem_movements using gin ((public.adreem_normalize_search_text(payload ->> 'note')) extensions.gin_trgm_ops);
create index adreem_movements_source_idx
  on public.adreem_movements (ledger_id, source_account_id, occurred_at desc)
  where source_account_id is not null;
create index adreem_movements_destination_idx
  on public.adreem_movements (ledger_id, destination_account_id, occurred_at desc)
  where destination_account_id is not null;
create index adreem_movements_dimension_idx
  on public.adreem_movements (ledger_id, dimension_id, sequence desc)
  where dimension_id is not null;
create index adreem_movements_expense_category_idx
  on public.adreem_movements (ledger_id, expense_category_id, sequence desc)
  where expense_category_id is not null;
create index adreem_entries_account_idx
  on public.adreem_movement_entries (ledger_id, account_id, created_at desc);
create index adreem_attachments_owner_idx
  on public.adreem_attachments (owner_id, updated_at desc);
create index adreem_recurring_due_idx
  on public.adreem_recurring_rules (owner_id, next_run_at)
  where status = 'active';
create index adreem_bot_state_expiry_idx
  on adreem_private.adreem_bot_state (expires_at)
  where expires_at is not null;
create index adreem_security_events_ledger_idx
  on adreem_private.adreem_security_events (ledger_id, owner_id, id desc);

create index adreem_accounts_ledger_owner_idx on public.adreem_accounts (ledger_id, owner_id);
create index adreem_dimensions_ledger_owner_idx on public.adreem_dimensions (ledger_id, owner_id);
create index adreem_dimensions_owner_idx on public.adreem_dimensions (owner_id, updated_at desc);
create index adreem_movements_ledger_owner_idx on public.adreem_movements (ledger_id, owner_id);
create index adreem_entries_ledger_owner_idx on public.adreem_movement_entries (ledger_id, owner_id);
create index adreem_entries_movement_idx on public.adreem_movement_entries (ledger_id, movement_id);
create index adreem_entries_owner_idx on public.adreem_movement_entries (owner_id, created_at desc);
create index adreem_attachments_ledger_owner_idx on public.adreem_attachments (ledger_id, owner_id);
create index adreem_attachments_movement_idx on public.adreem_attachments (ledger_id, movement_id);
create index adreem_attachments_account_idx on public.adreem_attachments (ledger_id, account_id);
create index adreem_attachments_account_recent_idx
  on public.adreem_attachments (ledger_id, account_id, updated_at desc, record_id desc)
  where account_id is not null and hidden_at is null;
create index adreem_recurring_ledger_owner_idx on public.adreem_recurring_rules (ledger_id, owner_id);
create index adreem_recurring_owner_idx on public.adreem_recurring_rules (owner_id, updated_at desc);
create index adreem_reconciliations_ledger_owner_idx on public.adreem_reconciliations (ledger_id, owner_id);
create index adreem_reconciliations_account_idx on public.adreem_reconciliations (ledger_id, account_id);
create index adreem_reconciliations_account_recent_idx
  on public.adreem_reconciliations (ledger_id, account_id, reconciled_at desc, record_id desc);
create index adreem_reconciliations_owner_idx on public.adreem_reconciliations (owner_id, reconciled_at desc);
create index adreem_audit_ledger_owner_idx on public.adreem_audit_events (ledger_id, owner_id);
create index adreem_audit_owner_idx on public.adreem_audit_events (owner_id, created_at desc);
create index adreem_ignored_ledger_owner_idx on public.adreem_ignored_external_accounts (ledger_id, owner_id);
create index adreem_ignored_owner_idx on public.adreem_ignored_external_accounts (owner_id, created_at desc);

create or replace function public.adreem_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.adreem_set_updated_at() from public;
grant execute on function public.adreem_set_updated_at() to authenticated, service_role;

drop trigger if exists adreem_profiles_set_updated_at on public.adreem_profiles;
create trigger adreem_profiles_set_updated_at before update on public.adreem_profiles
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_ledgers_set_updated_at on public.adreem_ledgers;
create trigger adreem_ledgers_set_updated_at before update on public.adreem_ledgers
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_accounts_set_updated_at on public.adreem_accounts;
create trigger adreem_accounts_set_updated_at before update on public.adreem_accounts
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_dimensions_set_updated_at on public.adreem_dimensions;
create trigger adreem_dimensions_set_updated_at before update on public.adreem_dimensions
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_movements_set_updated_at on public.adreem_movements;
create trigger adreem_movements_set_updated_at before update on public.adreem_movements
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_attachments_set_updated_at on public.adreem_attachments;
create trigger adreem_attachments_set_updated_at before update on public.adreem_attachments
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_recurring_rules_set_updated_at on public.adreem_recurring_rules;
create trigger adreem_recurring_rules_set_updated_at before update on public.adreem_recurring_rules
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_reconciliations_set_updated_at on public.adreem_reconciliations;
create trigger adreem_reconciliations_set_updated_at before update on public.adreem_reconciliations
for each row execute function public.adreem_set_updated_at();
drop trigger if exists adreem_bot_state_set_updated_at on adreem_private.adreem_bot_state;
create trigger adreem_bot_state_set_updated_at before update on adreem_private.adreem_bot_state
for each row execute function public.adreem_set_updated_at();

alter table public.adreem_profiles enable row level security;
alter table public.adreem_profiles force row level security;
alter table public.adreem_ledgers enable row level security;
alter table public.adreem_ledgers force row level security;
alter table public.adreem_accounts enable row level security;
alter table public.adreem_accounts force row level security;
alter table public.adreem_dimensions enable row level security;
alter table public.adreem_dimensions force row level security;
alter table public.adreem_movements enable row level security;
alter table public.adreem_movements force row level security;
alter table public.adreem_movement_entries enable row level security;
alter table public.adreem_movement_entries force row level security;
alter table public.adreem_attachments enable row level security;
alter table public.adreem_attachments force row level security;
alter table public.adreem_recurring_rules enable row level security;
alter table public.adreem_recurring_rules force row level security;
alter table public.adreem_reconciliations enable row level security;
alter table public.adreem_reconciliations force row level security;
alter table public.adreem_audit_events enable row level security;
alter table public.adreem_audit_events force row level security;
alter table public.adreem_ignored_external_accounts enable row level security;
alter table public.adreem_ignored_external_accounts force row level security;

create or replace function public.adreem_current_owner_is_active()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.adreem_profiles as profile
    where profile.id = (select auth.uid())
      and profile.is_active
      and lower(coalesce((select auth.jwt()) -> 'app_metadata' ->> 'adreem_member', 'false')) = 'true'
  );
$$;

revoke all on function public.adreem_current_owner_is_active() from public, anon, authenticated, service_role;
grant execute on function public.adreem_current_owner_is_active() to authenticated;

create policy adreem_profiles_select_own on public.adreem_profiles
for select to authenticated
using ((select auth.uid()) = id and (select public.adreem_current_owner_is_active()));
create policy adreem_profiles_update_own on public.adreem_profiles
for update to authenticated
using ((select auth.uid()) = id and (select public.adreem_current_owner_is_active()))
with check ((select auth.uid()) = id and (select public.adreem_current_owner_is_active()));

create policy adreem_ledgers_select_own on public.adreem_ledgers
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));

create policy adreem_accounts_own on public.adreem_accounts
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_dimensions_own on public.adreem_dimensions
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_movements_own on public.adreem_movements
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_entries_own on public.adreem_movement_entries
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_attachments_own on public.adreem_attachments
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_recurring_rules_own on public.adreem_recurring_rules
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_reconciliations_own on public.adreem_reconciliations
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_audit_events_own on public.adreem_audit_events
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));
create policy adreem_ignored_accounts_own on public.adreem_ignored_external_accounts
for select to authenticated
using (owner_id = (select auth.uid()) and (select public.adreem_current_owner_is_active()));

revoke all on table
  public.adreem_profiles,
  public.adreem_ledgers,
  public.adreem_accounts,
  public.adreem_dimensions,
  public.adreem_movements,
  public.adreem_movement_entries,
  public.adreem_attachments,
  public.adreem_recurring_rules,
  public.adreem_reconciliations,
  public.adreem_audit_events,
  public.adreem_ignored_external_accounts
from public, anon, authenticated, service_role;

revoke all on table adreem_private.adreem_bot_state from public, anon, authenticated, service_role;
revoke all on table adreem_private.adreem_security_events from public, anon, authenticated, service_role;

grant select on public.adreem_profiles to authenticated;
grant update (display_name, language) on public.adreem_profiles to authenticated;
grant select on public.adreem_ledgers to authenticated;
grant select on table
  public.adreem_accounts,
  public.adreem_dimensions,
  public.adreem_movements,
  public.adreem_movement_entries,
  public.adreem_attachments,
  public.adreem_recurring_rules,
  public.adreem_reconciliations,
  public.adreem_ignored_external_accounts
to authenticated;
grant select on public.adreem_audit_events to authenticated;

grant select on table
  public.adreem_profiles,
  public.adreem_ledgers,
  public.adreem_accounts,
  public.adreem_dimensions,
  public.adreem_movements,
  public.adreem_movement_entries,
  public.adreem_attachments,
  public.adreem_recurring_rules,
  public.adreem_reconciliations,
  public.adreem_audit_events,
  public.adreem_ignored_external_accounts
to service_role;

grant update (is_active) on public.adreem_profiles to service_role;

revoke all on sequence public.adreem_movements_sequence_seq from public, anon, authenticated, service_role;
revoke all on sequence adreem_private.adreem_security_events_id_seq from public, anon, authenticated, service_role;
